version: '3.4'
services:
  vncserver:
    env_file:
      - .env
    container_name: neuron-dev-vncserver-${ROS_DISTRO}
    image: neuronswkit/neuron-dev-vncserver:latest
    volumes:
      - x11-sock:/tmp/.X11-unix
    ports:
      - "6167:80"
  workspace:
    env_file:
      - .env
    container_name: neuron-dev-workspace-${ROS_DISTRO}
    image: neuronswkit/neuron-dev-workspace:${ROS_DISTRO}-0.1.0
    ports:
      - "6166:3000"
    volumes:
      - x11-sock:/tmp/.X11-unix
      - workspace:/workspace
      - ~/.gitconfig:/home/developer/.gitconfig
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    depends_on:
      - vncserver

volumes:
  x11-sock:
  workspace:
    external: false
    name: neuron-dev-workspace-${ROS_DISTRO}
