version: '2'
services:
  xserver:
    env_file:
      - .env
    container_name: neuron-dev-vncserver-${ROS_DISTRO}
    image: neuronsdk/neuron-dev-vncserver
    build: xserver
    ports:
      - "6167:80"
  workspace:
    env_file:
      - .env
    container_name: neuron-dev-workspace-${ROS_DISTRO}
    image: neuron-devcontainer/workspace
    build:
      context: distro/${ROS_DISTRO}
    ports:
      - "6166:3000"
    volumes:
      - workspace:/workspace
      - ~/.gitconfig:/home/developer/.gitconfig
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    volumes_from:
      - xserver
    depends_on:
      - xserver
volumes:
  workspace:
